### ISSUE TITLE
Invalid URL in Git command in README.md

### ISSUE THREAD

**Issue by jryburn** [Juniper/wistar#11]
In the README.md file it says the git command to clone the repo is:

`root@wistar-build:/opt/wistar# git clone https://github.com/nembery/wistar.git`

Appears that has been moved from nembery's personal account to Juniper so it should now be:

`root@wistar-build:/opt/wistar# git clone https://github.com/Juniper/wistar.git`

**Comment by nembery** [comment]
Fixed. Thanks for the catch!
