### ISSUE TITLE
wistar UI place items outside topology canvas makes them unusable

### ISSUE THREAD

**Issue by fr33l4ncer** [Juniper/wistar#13]
Wistar UI allows to open very limited amount of devices / bridges . It looks like past certain number of items (looks like 12 bridges) new ones are added outside canvas which makes them unusable

**Comment by nembery** [comment]
canvas resizing isn't currently possible. However, I have expanded the size of the canvas to be 4000 x 4000px with an overflow if necessary. This should make very large topologies (more) feasible. Fixed in commit: c766f60
