### ISSUE TITLE
pip crypto does not install when specifying version 1.2.1

### ISSUE THREAD

**Issue by bgriffin-** [Juniper/wistar#15]
----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Installing collected packages: cryptography, paramiko, lxml, ncclient, jinja2, scp, junos-eznc, Django, websocket-client
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-taXxJq/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yqa9I_-record/install-record.txt --single-version-externally-managed --compile:

 ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-taXxJq/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yqa9I_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-taXxJq/cryptography/

-----------------------------------------
Completes fine when version is left off pip install:
pip install pyvbox junos-eznc pyYAML Django==1.9.9 cryptography websocket-client

**Comment by nembery** [comment]
removed from README instructions. Thanks for the catch!
