### ISSUE TITLE
Networking not working due to interface type equals to e1000

### ISSUE THREAD

**Issue by dmontagner** [Juniper/wistar#16]
When the VMX template is using vre.js, the interface.type for the VFP is rendered out of the VCP jinja template instead of the VFP jinja template. 

The current `vre.js` has INTERFACE_TYPE set to `e1000`:

```
root@node2:/opt/wistar/common/static/js/vm_types# cat vre.js
draw2d.shape.node.vre = draw2d.shape.node.wistarSetParent.extend({
    NAME: "draw2d.shape.node.vre",
    VCPU: 1,
    VRAM: 512,
    ICON_WIDTH: 50,
    ICON_HEIGHT: 10,
    ICON_FILE: "/static/images/vre.png",

    INTERFACE_PREFIX: "ge-0/0/",
    INTERFACE_TYPE: "e1000",
```

This is only a problem when the e1000 driver doesn't work properly. I have seen installations where the e1000 driver works just fine.

I am currently testing fixes and debugging where the things are going wrong. For now, I fixed this manually in the DB and via `virsh edit`.

**Comment by nembery** [comment]
for fxp0 to come up, e1000 has to be specified on most versions. A full fix is incoming that splits out vre.js for specific versions like vre_15 and vre_latest
