### ISSUE TITLE
"Junos CLI Automation" sends junos command to child VMs(e.g. vFPC)

### ISSUE THREAD

**Issue by kazubu** [Juniper/wistar#6]
"Junos CLI Automation" sends junos command to child VMs(e.g. vFPC).
It consumes much time to wait timeout. It's feels bad. Please change to skip non-junos VMs.

https://qiita-image-store.s3.amazonaws.com/0/104974/996be18d-10f5-89f6-a3b9-99d23c03c8e6.png

**Comment by kazubu** [comment]
I have looked code and I guess that the root cause is b'junos_vpfe' contains "junos" and current code thinks it is Junos VM as code.

https://github.com/Juniper/wistar/blob/5c0f58171075362dc7c315f15071f4f0d4021308/ajax/views.py#L1157

**Comment by nembery** [comment]
Thanks for the report. Fix applied in commit: https://github.com/Juniper/wistar/commit/83d527423447eceef5ce39764b596f39da6c4e11 
Wistar will now determine if an instance is a 'child' instance and use that to no longer attempt direct access for things like Cli automation or boot up status.

**Comment by kazubu** [comment]
Thank you for the fix!
